right_of(X, Y) :- X =:= Y+1.
left_of(X, Y) :- right_of(Y, X).

next_to(X, Y) :- right_of(X, Y).
next_to(X, Y) :- left_of(X, Y).

all_diff(L) :- \+ (select(X,L,R), memberchk(X,R)).

question(Street, HasFish):-
    Street = [
        house(1, N1, C1, D1, S1, P1),
        house(2, N2, C2, D2, S2, P2),
        house(3, N3, C3, D3, S3, P3),
        house(4, N4, C4, D4, S4, P4),
        house(5, N5, C5, D5, S5, P5)],
    member(house(_, british, red, _, _, _), Street),
    member(house(1, norwegian, _, _, _, _), Street),
    member(house(A, norwegian, _, _, _, _), Street),
    member(house(B, _, blue, _, _, _), Street),
    next_to(A, B),
    member(house(C, _, green, _, _, _), Street),
    member(house(D, _, white, _, _, _), Street),
    left_of(C, D),
    member(house(_, _, green, coffee, _, _), Street),
    member(house(3, _, _, milk, _, _), Street),
    member(house(_, _, yellow, _, dunhill, _), Street),
    member(house(_, swedish, _, _, _, dog), Street),
    member(house(_, _, _, _, pallmall, bird), Street),
    member(house(E, _, _, _, marlboro, _), Street),
    member(house(F, _, _, _, _, cat), Street),
    next_to(E, F),
    member(house(_, _, _, beer, winfield, _), Street),
    member(house(G, _, _, _, _, horse), Street),
    member(house(H, _, _, _, dunhill, _), Street),
    next_to(G, H),
    member(house(_, german, _, _, rothmans, _), Street),
    member(house(I, _, _, _, marlboro, _), Street),
    member(house(J, _, _, water, _, _), Street),
    next_to(I, J),
    member(house(_, HasFish, _, _, _, fish), Street),
    Nationalities = [
        nationality(british),
        nationality(swedish),
        nationality(danish),
        nationality(norwegian),
        nationality(german)],
    member(nationality(N1), Nationalities),
    member(nationality(N2), Nationalities),
    member(nationality(N3), Nationalities),
    member(nationality(N4), Nationalities),
    member(nationality(N5), Nationalities),
    all_diff([N1,N2,N3,N4,N5]),
    Colors = [
        color(red),
        color(white),
        color(blue),
        color(yellow),
        color(green)],
    member(color(C1), Colors),
    member(color(C2), Colors),
    member(color(C3), Colors),
    member(color(C4), Colors),
    member(color(C5), Colors),
    all_diff([C1,C2,C3,C4,C5]),
    Drinks = [
        drink(milk),
        drink(beer),
        drink(tea),
        drink(water),
        drink(coffee)],
    member(drink(D1), Drinks),
    member(drink(D2), Drinks),
    member(drink(D3), Drinks),
    member(drink(D4), Drinks),
    member(drink(D5), Drinks),
    all_diff([D1,D2,D3,D4,D5]),
    Smokes = [
        smoke(pallmall),
        smoke(winfield),
        smoke(marlboro),
        smoke(dunhill),
        smoke(rothmans)],
    member(smoke(S1), Smokes),
    member(smoke(S2), Smokes),
    member(smoke(S3), Smokes),
    member(smoke(S4), Smokes),
    member(smoke(S5), Smokes),
    all_diff([S1,S2,S3,S4,S5]),
    Pets = [
        pet(bird),
        pet(dog),
        pet(horse),
        pet(cat),
        pet(fish)],
    member(pet(P1), Pets),
    member(pet(P2), Pets),
    member(pet(P3), Pets),
    member(pet(P4), Pets),
    member(pet(P5), Pets),
    all_diff([P1,P2,P3,P4,P5]).
